baseURL: 'https://northwestchill.github.io/band/'
languageCode: 'en-us'
title: Northwest Chill

disableKinds: 
  - "taxonomy"
  - "taxonomyTerm"
  - "section"

markup:
  goldmark:
    renderer:
      unsafe: true